### ISSUE TITLE
Probleme mit Umlauten in Dateinamen

### ISSUE THREAD

**Issue by schoebelh** [ddw17/picapport-docker#1]
Picapport erkennt leider Datei-/Pfadnamen mit enthaltenen Umlauten nicht. Nach meinem Verständnis müsste ins Dockerfile etwas in der Art aufgenommen werden um das zu lösen:

ENV LANG de_DE.UTF-8 oder/und
ENV LANGUAGE de_DE.UTF-8

Oder gibt es eine andere Lösung hierfür?

Danke...

**Comment by ddw17** [comment]
Hi Hagen, 
I hope it's ok to switch to English. 
Yes, you are right, umlauts did not work, but it never affected me. 
I made some changes, pushed them to a new branch  de_DE.UTF-8 and am currently uploading a new docker image tagged "picapport:10.2.00-de_DE.UTF-8" to docker hub. A short test looked ok. 
Could you give it a try if it solves your issues?

**Comment by schoebelh** [comment]
Hi David,
english is ok - i started in german cause i saw your post in the germ picapport support forum ;-).
I tried the new image and it seems quite ok now. Maybe you can export the language setting into the docker-compose file to remove the explicit image for german users?
Thank you for the support and the work on Docker Solution for Picapport...!

**Comment by poggenpower** [comment]
@schoebelh I just filed a PR, which should fix the issue with umlauts in a more generic way. No need to set the specific de_DE.UFT-8 locale.

**Comment by ddw17** [comment]
implemented by merging #5
