### ISSUE TITLE
Suggestion: ARM64 support

### ISSUE THREAD

**Issue by wechsler42** [ddw17/picapport-docker#6]
Hi there,
thanks for providing the Picapport Docker image. Do you have any plans to support the ARM64 architecture (like Raspberry Pi 4, etc.) besides AMD64?

**Comment by ddw17** [comment]
Hi wechlser42,
currently not. 
One could use qemu as whatever4711 does (see https://github.com/whatever4711/picapport), but since I neither need nor can test it, I don't intend to implement it. 
But feel free to fork and do it yourself :-)

**Comment by ddw17** [comment]
not "completed" but "not planned"
